language: 'node_js'
node_js: '11'
before_script:
- npm run build-storybook
script:
- echo "No tests avaliable"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: Codar97/tjjf-syllabus
  target_branch: gh-pages
  on:
    branch: master